# Generated by Django 3.0.4 on 2020-03-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.URLField(blank=True, help_text='Ingrese el enlace de una foto de perfil', max_length=1000, null=True),
        ),
    ]
