# Generated by Django 3.0.4 on 2020-03-09 01:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200308_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_creacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, help_text='Una frase favorita o como de describe.', max_length=255, null=True, verbose_name='Descripción:'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Autor Activo/No Activos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook (url)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram (url)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin (url)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter (url)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Web (url)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.URLField(blank=True, default='https://pwcenter.org/sites/default/files/styles/profile_image/public/default_images/default_profile.png?itok=wW1obErD', help_text='Pega el link de tu foto de: linkedin, facebook u otro. Le das click derecho a la imagen y seleccionas COPIAR DIRECCIÓN de la IMAGEN', max_length=1000, null=True),
        ),
    ]
