# Generated by Django 3.0.4 on 2020-03-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_universidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_creacion',
            new_name='date_creation',
        ),
    ]
