# Generated by Django 3.0.4 on 2020-03-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200309_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, help_text='Una frase favorita o como de describe.', max_length=255, null=True, verbose_name='Descripción:'),
        ),
    ]
