# Generated by Django 3.0.4 on 2020-03-10 06:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200309_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biografía o Experiencia'),
        ),
    ]
