# Generated by Django 3.0.4 on 2020-03-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200310_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono:'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad:'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook (url):'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram (url):'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin (url):'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.URLField(blank=True, default='https://pwcenter.org/sites/default/files/styles/profile_image/public/default_images/default_profile.png?itok=wW1obErD', help_text='Pega el link de tu foto de: linkedin, facebook u otro. Le das click derecho a la imagen y seleccionas COPIAR DIRECCIÓN de la IMAGEN', max_length=1000, null=True, verbose_name='Foto (URL):'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter (url):'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='universidad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Universidad:'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Web (url):'),
        ),
    ]
