# Generated by Django 3.0.4 on 2020-03-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200311_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.URLField(blank=True, default='https://pwcenter.org/sites/default/files/styles/profile_image/public/default_images/default_profile.png?itok=wW1obErD', help_text='Pega el link de tu foto de: linkedin, facebook u otro. Le das click derecho a la imagen y seleccionas COPIAR DIRECCIÓN de la IMAGEN', max_length=1000, null=True, verbose_name='Foto de perfil (URL):'),
        ),
    ]
