# Generated by Django 3.0.4 on 2020-03-26 01:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(blank=True, help_text='Te recomendamos diseñar el artículo en Word y pegar en esta parte.', null=True, verbose_name='Contenido:'),
        ),
    ]
