# Generated by Django 3.0.4 on 2020-03-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Imagen de portada (URL)'),
        ),
    ]
