# Generated by Django 3.0.4 on 2020-03-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, default='https://media-exp1.licdn.com/dms/image/C4E16AQGvG7p9NyHIAg/profile-displaybackgroundimage-shrink_200_800/0?e=1589414400&v=beta&t=fBQHmXrHd0Z4mD_BuXaFEC5jBp4Tq63JDy3Yg956UE4', null=True, verbose_name='Imagen de portada (URL)'),
        ),
    ]
