# Generated by Django 3.0.4 on 2020-03-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200311_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, default='https://www.karlosperu.com/wp-content/uploads/2019/09/conectividad.png', null=True, verbose_name='Imagen de portada (URL)'),
        ),
    ]
