# Generated by Django 3.0.4 on 2020-03-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200317_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
