# Generated by Django 3.0.4 on 2020-03-18 13:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Publicar, en cualquier momento puede editarlo.', null=True, verbose_name='Contenido:'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('datascience', 'Ciencia de datos'), ('neurociencia', 'Neurociencia'), ('education', 'Educación')], default='general', max_length=20, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Publicar/No publicar'),
        ),
    ]
