# Generated by Django 3.0.4 on 2020-03-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200318_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('datascience', 'Ciencia de datos'), ('neurociencia', 'Neurociencia'), ('projects', 'Proyectos')], default='general', max_length=20, null=True, verbose_name='Categoría'),
        ),
    ]
