# Generated by Django 3.0.4 on 2020-03-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200318_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Borrado/No borrado'),
        ),
    ]
