# Generated by Django 3.0.4 on 2020-03-18 13:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Una descripción breve del desafío', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('overview', ckeditor.fields.RichTextField(verbose_name='Describe el desafío.')),
                ('bases', ckeditor.fields.RichTextField(verbose_name='Describe las bases del desafío.')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.CharField(choices=[('individual', 'Individual'), ('institution', 'Institution')], default='institution', max_length=20)),
                ('status', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
